version: 1
build:
  tools:
    python: "3.8"

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .

sphinx:
  fail_on_warning: true
formats:
  - pdf
  - epub
